/**
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.regularExpression.impl;

import eu.numberfour.n4js.regex.regularExpression.EscapedCharacterClassAtom;
import eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Escaped Character Class Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EscapedCharacterClassAtomImpl extends CharacterClassAtomImpl implements EscapedCharacterClassAtom
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EscapedCharacterClassAtomImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RegularExpressionPackage.Literals.ESCAPED_CHARACTER_CLASS_ATOM;
  }

} //EscapedCharacterClassAtomImpl
