language: java

sudo: false

before_install:
  - export MAVEN_OPTS="-Xmx4048m -XX:-UseGCOverheadLimit"
  
jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

install: mvn -V -B -X -e clean verify -DnoVpn 
#install: mvn --version 

script: echo "done."
