language: java

sudo: false

before_install:
  - export MAVEN_OPTS="-Xmx4048m -XX:-UseGCOverheadLimit"
  
jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

#install: mvn -V -B -e clean verify -DnoVPN 
#install: mvn -V -B -X -e clean verify -DnoVPN 
install: 
  - mvn --version 
  - cat /proc/meminfo

#script: echo "done."
#script: mvn -V -B -e -q clean verify -DnoVPN -DnoTests
# Just run the resolution of the target platform:
script: mvn -V -B -e clean -DnoVPN -DnoTests
