:experimental:
:commandkey: &#8984;
:revdate: {localdate}
:toc:
:source-highlighter: prettify
:doctype: book
:data-uri:
:includesdir: _includes/

.Active Help Command Links
= Active Help Command Links

This is a brief test document to demonstrate some Command Links.

We can include command links by inserting javascript into the HTML (the asciidoc processing is bypassed).
The following URL
ifdef::eclipse[+++<a href='javascript:executeCommand("org.eclipse.ui.help.aboutAction")'> opens the About dialog</a>+++]
in eclipse. This is written more-or-less inline in Asciidoc.

Here's another test to see if we can generate some Live Help stuff:
ifdef::eclipse[+++<a href='javascript:liveAction("eu.numberfour.n4js.doc","eu.numberfour.n4js.doc.ActiveHelpOpenDialogAction","")'>Click here for a Message.</a>+++]
!!!


ifdef::eclipse[+++<a href='javascript:executeCommand("eu.numberfour.n4js.ui.wizard.CreateNewN4JSElementInModule.wizardId")'>opens NEW N4JS wizard</a>+++]




== Formatting

This section tests the formatting with two ifdefs side-by-side to reduce clutter in the source. The following URL
ifdef::eclipse[+++<a href='javascript:executeCommand("org.eclipse.ui.help.aboutAction")'> opens the About dialog</a>+++ in eclipse]
ifdef::website[is where our project page is hosted: http://numberfour.github.io/n4js/.]
I can write it more or less inline in Asciidoc.

== Asciidoc Source

Here's a quick look at the above Asciidoc source:

[source,asciidoc]
----
ifdef::eclipse[+++<a href='javascript:executeCommand("org.eclipse.ui.help.aboutAction")'>This is a Command Link</a>+++]
----

Will render as:

ifdef::eclipse[+++<a href='javascript:executeCommand("org.eclipse.ui.help.aboutAction")'>This is a Command Link</a>+++]

=== Whitespace

Whitespace must be deleted from the commands so asciidoc can process it as a single line,

[source,asciidoc]
ifdef::eclipse[+++<a href='javascript:liveAction("org.eclipse.platform.doc.isv","org.eclipse.platform.doc.isv.activeHelp.ActiveHelpOpenDialogAction","")'>Click here for a Message.</a>+++]

It may be possible to fix this using a block:

[source,asciidoc]
----
ifdef::eclipse[]
+++
<a href='javascript:liveAction(
	"org.eclipse.platform.doc.isv",
	"org.eclipse.platform.doc.isv.activeHelp.ActiveHelpOpenDialogAction",
	"")'>Click here for a Message.</a>
+++
endif::[]
----

Renders as:

ifdef::eclipse[]
+++
<a href='javascript:liveAction(
	"org.eclipse.platform.doc.isv",
	"org.eclipse.platform.doc.isv.activeHelp.ActiveHelpOpenDialogAction",
	"")'>Click here for a Message.</a>
+++
endif::[]

== Passthrough Asciidoc Processing

The use of the three plus symbols ``\+++`` will bypass the asciidoc processing and includes the raw string as a HTML link.
