/*
 * generated by Xtext
 */
package eu.numberfour.n4js.n4mf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.numberfour.n4js.n4mf.services.N4MFGrammarAccess;

public class N4MFParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private N4MFGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.numberfour.n4js.n4mf.parser.antlr.internal.InternalN4MFParser createParser(XtextTokenStream stream) {
		return new eu.numberfour.n4js.n4mf.parser.antlr.internal.InternalN4MFParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ProjectDescription";
	}
	
	public N4MFGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(N4MFGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
