/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRegularExpressionValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage.eINSTANCE);
		return result;
	}
	
}
