/*
 * generated by Xtext
 */
package eu.numberfour.n4js.regex.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRegularExpressionValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage.eINSTANCE);
		return result;
	}
}
