/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.ui;

import com.google.inject.Injector;
import eu.numberfour.n4js.regex.ui.internal.RegularExpressionActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RegularExpressionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RegularExpressionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RegularExpressionActivator.getInstance().getInjector(RegularExpressionActivator.EU_NUMBERFOUR_N4JS_REGEX_REGULAREXPRESSION);
	}
	
}
