/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.numberfour.n4js.common.unicode.UnicodeStandaloneSetup;
import eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class RegularExpressionStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		UnicodeStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new RegularExpressionRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.numberfour.eu/n4js/regex/RegularExpression")) {
			EPackage.Registry.INSTANCE.put("http://www.numberfour.eu/n4js/regex/RegularExpression", RegularExpressionPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("regex", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("regex", serviceProvider);
	}
}
