= Introduction

This specification defines the N4JS language.

In general, the N4 JavaScript dialect used is identical to the standard
ECMAScript as defined in the 6th edition of ECMA-262, also known as
ECMAScript 2015, referred to as cite:[ECMA15a].

== Notation

=== Grammar Notation

For the specification of the syntax and structure of elements, we use a
slightly augmented similar to the grammar language of Xtext http://www.eclipse.org/Xtext/documentation.html\#grammarLanguage[Grammar Language].

Similar to cite:[ECMA11a], we define types with properties only for the purpose of
explanation and usage within this specification. We use the Xtext
notation style to assign values to meta-properties. Particularly, we use
the Xtext notation for collection (``+=``) and boolean (``?=``) values. These
properties are written in italics. Enumerations are defined similar to
Xtext. In order to allow the specification of default values, which are
often defined by omitting the value, we always define the literal
explicitly if it can be defined by the user.

The following lists informally defines the grammar:

Terminal::
  Terminals (or terminal strings) are enclosed in single quotes, e.g., ``terminal``.
Enumerations::
  Rules which contain only terminals used as values for properties are
  marked with ``enum`` for enumeration.
Properties::
  Values of non-terminals, e.g., other rules, can be assigned to
  properties. The property name and the assignment are not part of the
  original syntax and only used for the meta description. E.g., ``__name=__Identifier``.
Collection Properties::
  If a property is a collection, values are added to that list via ``+=``.
  E.g.,``__property+=__Value`` .
Boolean Properties::
  Boolean properties are set to false by default, if the value (usually
  a terminal) is found, the boolean value is set to true. Often, the
  name of the property is similar to the terminal. E.g., ``__final?__='final'?``.

Properties of a non-terminal are sometimes listed again below the
grammar. In that case, often pseudo properties are introduced which are
derived from other properties and which are only used for
simplification.

=== Type Judgments and Rules and Constraints Notation

==== Typing Rules and Judgments

.Rule
[def]
--
We use the common notation for rules such as type
inference rules
footnote:[A brief introduction can be found at http://www.cs.cornell.edu/~ross/publications/mixedsite/tutorial.html. In general, we refer the reader to cite:[Pierce02a]]
, that is

math:[\[ \frac{premises}{conclusion} \hspace{5mm} \textrm{rule name} \] ]

math:[$premises$] is the rule’s premises (e.g., the expression to
be inferred), math:[$conclusion$] the result of the rule.
math:[$rule name$] is an optional condition which may be omitted.


Both parts of the rule may contain multiple expressions, which are
concatenated via and. For example, the following
math:[\[\begin{aligned} \frac{P_1 \hspace{5mm}  P_2 \hspace{5mm} P_3}{C} \end{aligned}\]] can be read as
' ``if math:[$P_1$], math:[$P_2$], and math:[$P_3$] are all true, then math:[$C$] is true as well`` '.
--

The following judgments (with relation symbols) are used:

// TODO replace math with original LaTeX
subtype ``<`` ::
+
type``:`` ::
  in which the left hand side is a declaration or
  expression, and the right hand side a type. We also use
  math:[$\infType{..}$] as a function returning the (inferred) type
  of an expression.
expectedTypeIn math:[$ \lhd :$] ::
   a relation with three arguments:
  math:[$container \lhd expression: type$] means, that
  math:[$expression$] is expected to be a subtype of
  math:[$type$] inside math:[$container$]

The following statement, for example, defines transitivity of subtypes
(in a simplified manner):

// TODO replace math with original LaTeX
math:[\[\begin{aligned} \frac{\Gamma B \vdash <: A \hspace{7mm} \Gamma \vdash C <: B}{\Gamma \vdash C: < A}\end{aligned}\]]

is the context containing (bound) type variables etc.,
math:[$\entails$] can be read as ``entails``. Thus, the rule can be
read as follows: if the type B is a subtype of type A in context (i.e.
with constraints on type variables specified in ), and if type C is a
subtype of B, then C is also a subtype of A in context .

In rules, we sometimes omit the environment if it is not needed. New
information is sometimes added to the environment, in particular,
substitutions (that is binding type variables to a type). The set of
substitutions is written with math:[$\typeSubs$] (theta). If new
substitutions are explicitly added to that set, we write
math:[$\typeSubs(V \leftarrow T)$] (math:[$V$] is substituted
with type math:[$T$]). Often, these bindings are computed from a
parameterized type reference which declares type arguments which are
bound to the type variables of the generic declaration. In this case we
simply write math:[$\typeSubs(p)$], in which math:[$p$] is the
parameterized type declaration. As these new substitutions must become
part of a (newly) created environment, we then usually write
math:[$\typeEnvAdd \typeSubs(p)$]. These substitutions are usually
omitted.


==== Types of an Element

A variable or other typed element may be associated with three types:

1.  Declared type: the type explicitly specified in the code, e.g., .
2.  Inferred type: the type inferred by the type inferencer, e.g.,
infers the type of s to ``string``. I.e.
math:[$\Gamma \vdash s :{string}$] will be true, or
math:[$[\![s]\!] < :string $\]]. If an element is
annotated with a type ,i.e. it has a declared type, the inferred type
will always be the declared type.
3.  Actual type: the actual type of a variable during runtime. This type
information is not available at compile time and ignored in this
specification.

These types are not type declarations but type references, in fact, as
they may be parameterized. For the sake of simplicity, we often omit the
``Ref`` suffix to shorten formulas. Consequently, we define the
following properties and pseudo properties for typed elements such as
variables:

The explicitly declared type, this is usually a real property of the
construct. Not all elements allow the specification of a declared type,
such as expressions.

or math:[$\infType{..}$]: This pseudo property is the inferred type
computed by the type inferencer.

A pseudo property for elements with a math:[$declaredType$]
property. It is similar to the inferred type, i.e.
math:[$e.type = \infType{e}$]

== Auxiliary Functions

This section describes some auxiliary functions required for definition
of type inference rules later on.

=== Binding

Binding an identifier (variable reference) to a variable declaration (or
variable definition) is not part of this specification as this is
standard ECMAScript functionality. However, some valid ECMAScript
bindings are permitted due to visibility constraints.

.Binding Relation
[def]
--
We define a pseudo relation
math:[\[\begin{aligned} bind: VariableReference \times VariableDeclaration\end{aligned}\]]
which binds a reference, i.e. an identifier, to a declaration (e.g.,variable
declaration).

Binding of variable references to declaration is defined by ECMAScript
already. Type references only occur in type expressions, how these are
handled is explained in [sec:_type-expressions].

We usually omit this binding mechanism in most rules and use the
reference similarly to the declaration or definition it is bound to. If
a variable reference math:[$r$], for example, is bound to a
variable declaration math:[$D$], i.e. math:[$bind(r,D)$], we
simply write math:[$r.type$] instead of
math:[$bind(r,D), D.type$] to refer to the type expression (of the
variable).
--

footnote:[One can interpret this similar to delegate methods, that is, instead of writing ``r.binding().getType()``, a method ``r.getType()\{return binding().getType();`` is defined.]

A ``DeclaredType`` references the type declaration by its simple name that has been
imported from a module specifier. We define the method
math:[$bind$] for declared types as well:

.Binding Relation of Types
[def]
--
We define a pseudo relation
math:[\[\begin{aligned} bind: DeclaredType \times Class|Interface|Enum\end{aligned}\]]
which binds a type reference, i.e. a simple name, to the type declaration.
--

=== Merging Types

In some cases we have to merge types, e.g., types of a union type or
item types of an array. For that purpose, we define a method
math:[$merge$] as follows.

.Merge Function
[def]
--
We define a pseudo function
math:[\[\begin{aligned}
merge: Type \times \dots \times Type \to \powerset(Type)\end{aligned}\]]

The idea of this function is to remove duplicates. For example; if a
union type contains two type expressions math:[$te_1$] and
math:[$te_k$], and if math:[$\tau(te_1)=\tau(te_2)$], then
math:[$merge(\tau(te_1), \tau(te_2))$] contains only one element.
The order of the elements is lost, however.
--

==== Logic Formulars

In general, we use a pragmatic mixture of pseudo code, predicate logic,
and OCL. Within constraints (also within the inference rules), the
properties defined in the grammar are used.

In some rules, it is necessary to type the rule variables. Instead of
explicitly checking the metatype (via
math:[$\mu(X)=:{MetaType}$]), we precede the variable with the
type, that is: math:[$:{MetaType} X$].

Instead of ``type casting`` elements, often properties are simply
accessed. If an element does not define that element, it is either
assumed to be false or null by default.

If a property math:[$p$] is optional and not set, we write
math:[$p=null$] to test its absence. Note that math:[$p=null$]
is different from math:[$p=Null$], as the latter refers to the null
type. Non-terminals may implicitly be subclasses. In that case, the
concrete non-terminal, or type, of a property may be subject for a test
in a constraint.

=== Symbols and Font Convention

Variables and their properties are printed in italic when used in
formulas (such as rules). A dot-notation is used for member access, e.g.
math:[$v.name$]. Also defined functions are printed in italic,
e.g., math:[$acc(r,D)$]. Properties which define sets are usually
ordered and we assume 0-indexed access to elements, the index
subscripted, e.g., math:[$v.methods_i$].

We use the following symbols and font conventions:

//TODO: math processor test section:

math:[$\land$], math:[$\lor$], math:[$\lxor$],
math:[$\lnot$]::
  Logical and, or, exclusive or (xor), and not.
math:[$\to$], math:[$\iff$],
math:[$\lif .. \lthen .. \lelse$]::
  Logical implication, if and only if, and if-then-else.
math:[$\TRUE$], math:[$\FALSE$], math:[$\NULL$],
math:[$\emptyset$]::
  Boolean true, boolean false, null (i.e., not specified, e.g.,
  math:[$v.sup=\null$] means that there are is no math:[$sup$]
  (super class) specified), empty set.
math:[$\in$], math:[$\notin$], math:[$\cup$],
math:[$\cap$], math:[$|x|$]::
  Element of, not an element of, union set, intersection set,
  cardinality of set x.
math:[$\powerset (X)$]::
  Power set of math:[$X$], i.e.
  math:[$\powerset(X) = \{ U: U \subseteq X \}$].
math:[$\exists$], math:[$\nexists$], math:[$\forall$]::
  Exists, not exists, for all; we write
  math:[$\exists x,...,z: P(x,...,z)$] and say ``there exists
  math:[$x,...,z$] such that predicate math:[$P$] is true``.
  Note that math:[$\nexists x: P(x) \iff \forall x: \lnot P(x)$].
math:[$\mu(..)$]::
  (mu) read ``metatype of``; metatype of a variable or property, e.g.,
  math:[$\lif \mu(x)=:{Class} \lthen ... \lelse ...$] .
math:[$\seq{x}$]::
  Sequence of elements math:[$x_1,\dots,x_n$]. E.g., if we want to
  define a constraint that the owner of a members of a class
  math:[$C$] is the class, we simply write
  math:[\[\begin{aligned}
  &C.\seq{members}.owner = C\end{aligned}\]] instead of
  math:[$\forall m \in C.members: m.owner=C$] or even more
  complicated with index variables.

Sequences are 1-based, e.g., a sequence math:[$s$] with length
math:[$|s|=n$], has elements math:[$s_1, \dots, s_n$].
