/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRegularExpressionScopeProvider extends DelegatingScopeProvider {
}
