/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.ts.parser.antlr;

import com.google.inject.Inject;
import eu.numberfour.n4js.ts.parser.antlr.internal.InternalTypesParser;
import eu.numberfour.n4js.ts.services.TypesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TypesParser extends AbstractAntlrParser {

	@Inject
	private TypesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_EOL");
	}
	

	@Override
	protected InternalTypesParser createParser(XtextTokenStream stream) {
		return new InternalTypesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TypeDefs";
	}

	public TypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
