/*
 * generated by Xtext
 */
package eu.numberfour.n4js.ts.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.numberfour.n4js.ts.services.TypesGrammarAccess;

public class TypesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TypesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_EOL");
	}
	
	@Override
	protected eu.numberfour.n4js.ts.parser.antlr.internal.InternalTypesParser createParser(XtextTokenStream stream) {
		return new eu.numberfour.n4js.ts.parser.antlr.internal.InternalTypesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TypeDefs";
	}
	
	public TypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
