/*
 * generated by Xtext
 */
package eu.numberfour.n4js.ts.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TypesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/numberfour/n4js/ts/parser/antlr/internal/InternalTypesParser.tokens");
	}
}
