/*
 * generated by Xtext
 */
package eu.numberfour.n4js.ts.formatting2;

import org.eclipse.xtext.formatting2.AbstractFormatter2

abstract class TypeExpressionsFormatter extends AbstractFormatter2 {
}
