/*
 * generated by Xtext
 */
package eu.numberfour.n4jsx;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class N4JSXStandaloneSetup extends N4JSXStandaloneSetupGenerated{

	public static void doSetup() {
		new N4JSXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

