/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.ts;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.numberfour.n4js.common.unicode.UnicodeStandaloneSetup;
import org.eclipse.xtext.ISetup;

@SuppressWarnings("all")
public class TypeExpressionsStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		UnicodeStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new TypeExpressionsRuntimeModule());
	}
	
	public void register(Injector injector) {
	}
}
