/*
 * generated by Xtext
 */
package eu.numberfour.n4jsx.ui.labeling

import eu.numberfour.n4js.ui.labeling.N4JSDescriptionLabelProvider

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
class N4JSXDescriptionLabelProvider extends N4JSDescriptionLabelProvider {
}
