/*
 * generated by Xtext
 */
package eu.numberfour.n4jsx.ui.outline

import eu.numberfour.n4js.ui.outline.N4JSOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class N4JSXOutlineTreeProvider extends N4JSOutlineTreeProvider {

}
