/*
 * generated by Xtext
 */
package eu.numberfour.n4jsx.ui.quickfix

import eu.numberfour.n4js.ui.quickfix.N4JSQuickfixProvider

//import org.eclipse.xtext.ui.editor.quickfix.Fix
//import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor
//import org.eclipse.xtext.validation.Issue
/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class N4JSXQuickfixProvider extends N4JSQuickfixProvider {
}
