/**
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.regularExpression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Escaped Character Class Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage#getEscapedCharacterClassAtom()
 * @model
 * @generated
 */
public interface EscapedCharacterClassAtom extends CharacterClassAtom
{
} // EscapedCharacterClassAtom
