/**
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.regularExpression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Start</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see eu.numberfour.n4js.regex.regularExpression.RegularExpressionPackage#getLineStart()
 * @model
 * @generated
 */
public interface LineStart extends Assertion
{
} // LineStart
