/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.ts.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTypesScopeProvider extends DelegatingScopeProvider {
}
