/*
 * generated by Xtext
 */
package eu.numberfour.n4js.regex.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.numberfour.n4js.regex.services.RegularExpressionGrammarAccess;

public class RegularExpressionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RegularExpressionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected eu.numberfour.n4js.regex.parser.antlr.internal.InternalRegularExpressionParser createParser(XtextTokenStream stream) {
		return new eu.numberfour.n4js.regex.parser.antlr.internal.InternalRegularExpressionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RegularExpressionLiteral";
	}
	
	public RegularExpressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RegularExpressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
