/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RegularExpressionAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/numberfour/n4js/regex/parser/antlr/internal/InternalRegularExpressionParser.tokens");
	}
}
