/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.regex.parser.antlr;

import com.google.inject.Inject;
import eu.numberfour.n4js.regex.parser.antlr.internal.InternalRegularExpressionParser;
import eu.numberfour.n4js.regex.services.RegularExpressionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RegularExpressionParser extends AbstractAntlrParser {

	@Inject
	private RegularExpressionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	

	@Override
	protected InternalRegularExpressionParser createParser(XtextTokenStream stream) {
		return new InternalRegularExpressionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RegularExpressionLiteral";
	}

	public RegularExpressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RegularExpressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
