/*
 * generated by Xtext
 */
package eu.numberfour.n4jsx.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.numberfour.n4jsx.services.N4JSXGrammarAccess;

public class N4JSXParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private N4JSXGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_EOL");
	}
	
	@Override
	protected eu.numberfour.n4jsx.parser.antlr.internal.InternalN4JSXParser createParser(XtextTokenStream stream) {
		return new eu.numberfour.n4jsx.parser.antlr.internal.InternalN4JSXParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "IDLScript";
	}
	
	public N4JSXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(N4JSXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
