/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4jsx.parser.antlr;

import com.google.inject.Inject;
import eu.numberfour.n4jsx.parser.antlr.internal.InternalN4JSXParser;
import eu.numberfour.n4jsx.services.N4JSXGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class N4JSXParser extends AbstractAntlrParser {

	@Inject
	private N4JSXGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_EOL");
	}
	

	@Override
	protected InternalN4JSXParser createParser(XtextTokenStream stream) {
		return new InternalN4JSXParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IDLScript";
	}

	public N4JSXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(N4JSXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
